name: MarketObserver
host: 127.0.0.1
port: 8001
log_level: "INFO"
grpc_host: "127.0.0.1"
grpc_port: 50051

storage:
  db_type: postgres
  db_path: market-observer.db
  # DB source list for symbol to fetch/follow
  # example: "schema.table.field"
  db_connection_string: postgresql://user:password@localhost/dbname
  postgres_mode: both

# --- NATS CONNECTION & JETSTREAM CONFIGURATION ---
nats:
  # Connection Details
  servers: 
    - "nats://127.0.0.1:4222"
    # You can list multiple servers for redundancy:
    # - "nats://nats.staging.example.com:4222"
  
  client_id: "NATSmarketobserver" # Unique ID for this client instance
  cluster_id: "" # Only used for legacy NATS Streaming (often left empty)
  subject: "tick.raw" # Default subject to publish to
  subject_prefix: "tick" # Base prefix for all subjects 

  # Reliability and Timeouts (Use Go time.Duration format)
  connect_timeout: "5s"
  reconnect_wait: "1s"
  max_reconnects: 10
  flush_timeout: "5s" # Max time to wait for published messages to be acknowledged

  # JetStream Settings (Requires JetStream enabled on the NATS server)
  jetstream:
    enabled: false
    stream_name: "TICK_DATA" # The name of the stream to publish to

    # Stream Configuration (How the data is stored)
    subjects: 
      - "tick." # Subjects the stream tracks (e.g., all subjects starting with orderbook.)
    retention: "limits" # Limits-based retention is typical for trading data
    storage: "file" # Store data on disk (more durable than 'memory')
    replicas: 1 # Number of copies of the stream data (1 for local, 3 for cluster)

    # Stream Limits
    max_age: "72h" # Keep messages for 72 hours (3 days)
    max_msgs: -1 # Unlimited number of messages
    max_bytes: 10737418240 # 10GB limit (10 * 1024 * 1024 * 1024 bytes)
    max_msg_size: 1048576 # 1MB max size per message (1024 * 1024 bytes)

    # Optional: Consumer Configuration (often defined externally, but included for completeness)
    durable_consumer: "DATA_TICK_CONSUMER" 
    ack_wait: "30s" # Time to wait for an acknowledgment from a consumer

network:
  enabled: false
  timeout: 10
  retries: 3
  concurrent_requests: 25
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  proxies: []

# windows_aggregation parsed with ParseDuration: 
# A duration string is a possibly signed sequence of decimal numbers, 
# each with optional fraction and a unit suffix, such as :
# "300ms", "-1.5h" or "2h45m". 
# Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
windows_aggregation:
  - 5m
  - 10m
  - 15m
  - 30m
  - 1h
  - 2h
  - 4h
  - 6h

data_source:
  data_retention_days: 7
  update_interval_seconds: 300
  sources:
    # Example NATS Streaming connector (ensure only ONE source is enabled)
    # - name: "NATS Stream"
    #   type: "nats"
    #   enabled: false
    #   symbols: [] # Leave empty for all, or specify symbols
    - name: "Yahoo Finance"
      type: "yahoo"
      enabled: true
      symbols:
      # for postgres database we can load symbol from a table
      # example: "schema.table.field"
        - AAPL
        - MSFT
        - GOOGL
        - AMZN
        - NVDA
        - TSLA
        - META
        - BRK-B
        - UNH
        - JNJ
        - JPM
        - XOM
        - V
        - PG
        - MA
        - HD
        - CVX
        - ABBV
        - MRK
        - PEP
        - LULU
        - RCL
        - AVGO
        - COST
        - CSCO
        - MCD
        - WMT
        - TMO
        - BAC
        - CRM
        - PFE
        - KO
        - LIN
        - WFC
        - AMD
        - DIS
        - DHR
        - TXN
        - PM
        - MS
        - NKE
        - NEE
        - UPS
        - BMY
        - RTX
        - AMGN
        - HON
        - T
        - BA
        - IBM
        - UNP
        - LOW
        - ELV
        - SPGI
        - CVS
        - CAT
        - GS
        - DE
        - LMT
        - INTU
        - QCOM
        - PLD
        - SCHW
        - BLK
        - ORCL
        - AMT
        - GILD
        - SBUX
        - C
        - ISRG
        - AXP
        - MDT
        - NOW
        - ZTS
        - SYK
        - EL
        - TJX
        - ADP
        - C
        - MO
        - CB
        - MMC
        - GE
        - ADI
        - TMUS
        - VRTX
        - EOG
        - SO
        - REGN
        - CI
        - BDX
        - PYPL
        - FISV
        - BSX
        - AON
        - ITW
        - CL
        - APD
        - EW
        - PANW
        - CHTR
        - ETN